spring:
  application:
    name:
      request-logger-store
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      validation-timeout: 3000
      leak-detection-threshold: 5000
      idle-timeout: 60000
      max-lifetime: 1800000

    jpa:
      hibernate:
        use-new-id-generator-mappings: false
      show-sql: true
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
app:
  data-dir: data
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      enable-idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092
resilience4j.circuitbreaker:
  configs:
    default:
      failure-rate-threshold: 2   # процент ошибок, при котором цепь разрывается
      minimum-number-of-calls: 2    # минимум вызовов для оценки состояния
      sliding-window-size: 3      # за последние N вызовов
      sliding-window-type: COUNT_BASED
      wait-duration-in-open-state: 10s  # сколько будет в состоянии OPEN
      permitted-number-of-calls-in-half-open-state: 3  # сколько можно по
server:
  port: 8080

